### PR TITLE
Update docs pending deployment of new namespace subdomain

### PR DESCRIPTION
**Pull request by mcdan**
We will be making a change to Runtime to support better segregation of web actions. These docs accompany those changes. Deployment date TBD so please do not push to production just yet.

### CODE REVIEW

**Comment by macdonst** [comment]
@MattLusher this PR looks good to me but I don't specifically work on runtime and it would make more sense for someone on Dan's team to give this change the 👍

**Comment by MattLusher** [comment]
@macdonst You mean Dan McWeeny? He submitted this. Would you recommend Nick Halbakken, then? Or Mihai Corlan?

**Comment by mcorlan** [comment]
This is all good! I talked with Dan. We just need to wait for the release and then we can publish this. thank you!

**Comment by MattLusher** [comment]
Thanks, guys! BTW, my contract terminates tomorrow, so I'll no longer be able to officially work on the docs. However, I don't mind keeping an eye on them, and my GitHub account will still have perms. Ping me whenever you like, either through GitHub or directly at mattlusher@outlook.com.

**Comment by mcorlan** [comment]
Thank you Matt for your support! It was a pleasure working with you. Wish you all the best.

**Comment by mcdan** [comment]
@mcorlan - This can get merged now, thanks.

**Comment by mcorlan** [comment]
Done @mcdan ! Thank you!

**Pull request merged**
